exclude_paths:
  - tmp
  - vendor

detectors:
  BooleanParameter:
    exclude:
      - "Cogger#initialize"
  LongParameterList:
    enabled: false
  ModuleInitialize:
    exclude:
      - "Cogger"
  TooManyStatements:
    exclude:
      - "Cogger::Registry#self.extended"
