exclude_paths:
  - tmp
  - vendor

detectors:
  BooleanParameter:
    exclude:
      - "Cogger#initialize"
  DataClump:
    exclude:
      - "Cogger::Hub"
  LongParameterList:
    enabled: false
  ModuleInitialize:
    exclude:
      - "Cogger"
