inherit_gem:
  caliber: config/all.yml

Metrics/AbcSize:
  Exclude:
    - "lib/cogger/registry.rb"
Metrics/MethodLength:
  Exclude:
    - "lib/cogger/registry.rb"
Metrics/ParameterLists:
  Exclude:
    - "lib/cogger/configuration.rb"
