inherit_gem:
  caliber: config/all.yml

Metrics/AbcSize:
  Exclude:
    - "lib/cogger/configuration.rb"
    - "lib/cogger/registry.rb"
Metrics/MethodLength:
  Exclude:
    - "lib/cogger/registry.rb"
Metrics/ParameterLists:
  Exclude:
    - "lib/cogger/configuration.rb"
    - "lib/cogger/entry.rb"
Naming/PredicateMethod:
  AllowedMethods:
    - dispatch
    - crash
